export default <AppItem[]>[
  {
    homepage: 'https://bms.zhimeiguoji.cn/',
    repository: 'https://git.zhimeiguoji.com/zhimei',
    icon: 'zhimei.png',
    keywords: ['bms', 'zhimei'],
    name: 'BMSv1',
    lessRadius: true,
  },
  {
    homepage: 'http://192.168.2.16:8000/',
    repository: '',
    icon: 'yearning.png',
    keywords: ['yearning', 'db', 'sql'],
    name: '数据库审计系统',
    lessRadius: true,
  },
  {
    homepage: 'http://192.168.2.16:8001/',
    repository: '',
    icon: 'devops.png',
    keywords: ['devops', 'dev', 'test', 'git', 'gj'],
    name: '构建和发布',
    lessRadius: true,
  }, 
  {
    homepage: 'http://zm.zhimeiguoji.com:8188',
    repository: '',
    icon: 'gateway.png',
    keywords: ['10.188','188'],
    name: '192.168.10.188',
    lessRadius: true,
  },
  {
    homepage: 'http://zm.zhimeiguoji.com:8210',
    repository: '',
    icon: 'gateway.png',
    keywords: ['10.210','210'],
    name: '192.168.10.210',
    lessRadius: true,
  },
  {
    homepage: 'http://zm.zhimeiguoji.com:8211',
    repository: '',
    icon: 'gateway.png',
    keywords: ['10.211','211'],
    name: '192.168.10.211',
    lessRadius: true,
  },
  {
    homepage: 'http://zm.zhimeiguoji.com:8200',
    repository: '',
    icon: 'gateway.png',
    keywords: ['12.200','200'],
    name: '192.168.12.200',
    lessRadius: true,
  },{
    homepage: 'http://zm.zhimeiguoji.com:8201',
    repository: '',
    icon: 'gateway.png',
    keywords: ['12.201','201'],
    name: '192.168.12.201',
    lessRadius: true,
  },
  {
    homepage: 'http://zm.zhimeiguoji.com:8222',
    repository: '',
    icon: 'gateway.png',
    keywords: ['14.222','222'],
    name: '192.168.14.222',
    lessRadius: true,
  },
  {
    homepage: 'http://192.168.2.189',
    repository: '',
    icon: 'gateway.png',
    keywords: ['2.189','189'],
    name: '192.168.2.189',
    lessRadius: true,
  },
  {
    homepage: 'http://192.168.2.215',
    repository: '',
    icon: 'gateway.png',
    keywords: ['2.189','189'],
    name: '开发2.215',
    lessRadius: true,
  },
  {
    homepage: 'https://ip.zhimeiguoji.cn',
    repository: '',
    icon: 'ip.png',
    keywords: ['ip','白名单','whitelist','white','list'],
    name: '白名单',
    lessRadius: true,
  },
  {
    homepage: 'http://zm.zhimeiguoji.com:3300',
    icon: 'cewangsu.png',
    keywords: ['net', 'cesu', 'cs', 'cewangsu', 'cws'],
    name: '云测速',
    lessRadius: true,
  },
  {
    homepage: 'http://192.168.2.16:8811/',
    repository: '',
    icon: 'network.png',
    keywords: ['内网穿透','nps', 'nw'],
    name: 'NPS管理',
    lessRadius: true,
  },
  {
    homepage: 'https://ref.rootcs.cn/',
    repository: '',
    icon: 'quickreference.png',
    keywords: ['ref','docs'],
    name: '备忘录',
    lessRadius: true,
  },
  {
    homepage: 'https://convertio.co/zh/',
    repository: '',
    icon: 'convertio.png',
    keywords: ['ref','docs'],
    name: 'svg转png',
    lessRadius: true,
  },
  {
    homepage: 'https://vectorizer.ai/',
    repository: '',
    icon: 'vectorizer.png',
    keywords: ['ref','docs'],
    name: 'png转svg',
    lessRadius: true,
  },
  {
    homepage: 'http://192.168.2.16:9200',
    repository: '',
    icon: 'network2.png',
    keywords: ['cpolar','nps', 'dev', 'test'],
    name: 'cpolar',
    lessRadius: true,
  },
  {
    homepage: 'https://192.168.2.30:38677/6ee68c75',
    repository: '',
    icon: 'vs.png',
    keywords: ['vs','30'],
    name: 'VS30开发',
    lessRadius: true,
  },
  {
    homepage: 'https://192.168.2.31:39306/a868bbcf',
    repository: '',
    icon: 'vs.png',
    keywords: ['vs','31'],
    name: 'VS31测试',
    lessRadius: true,
  },
  {
    homepage: 'http://bmsdocs.zhimeiguoji.cn/',
    icon: 'link.png',
    keywords: ['bms', 'bmsdocs'],
    name: 'BMS文档'
  }
]
