export default <AppItem[]>[
  {
    homepage: 'https://cloud.tencent.com/login',
    repository: '',
    icon: 'link.png',
    keywords: ['txy', '腾讯云', 'fwq', 'vs'],
    name: '腾讯云',
    lessRadius: true,
  },
  {
    homepage: 'https://www.winnerlook.com/',
    repository: '',
    icon: 'link.png',
    keywords: ['ax', 'axe', '虚拟号', '小号'],
    name: '云信留客',
    lessRadius: true,
  },
  {
    homepage: 'https://gitee.com',
    repository: '',
    icon: 'link.png',
    keywords: ['gitee', 'git', '代码'],
    name: 'Gitee',
    lessRadius: true,
  },
  {
    homepage: 'https://git.zhimeiguoji.com/help/ci/quick_start/index.md',
    repository: '',
    icon: 'link.png',
    keywords: ['gitlab', 'ci', 'cd'],
    name: 'GitlabCi',
    lessRadius: true,
  },
  {
    homepage: 'https://www.nginx-cn.net/',
    icon: 'link.png',
    keywords: ['nginx', 'f5', 'fz', '负载均衡', 'fzjh', 'jh'],
    name: 'Nginx负载均衡',
  },
  {
    homepage: 'https://d2.pub/doc/d2-advance/',
    repository: 'https://github.com/d2-projects/d2-advance',
    icon: 'link.png',
    keywords: ['d2admin', 'ui'],
    name: 'd2admin模板v2',
  },
  {
    homepage: 'https://d2.pub/',
    repository: 'https://github.com/d2-projects/d2-admin',
    icon: 'link.png',
    keywords: ['d2admin', 'ui'],
    name: 'd2admin模板v1',
  },
  {
    homepage: 'https://d2.pub/doc/d2-admin/',
    repository: 'https://github.com/d2-projects/d2-admin',
    icon: 'link.png',
    keywords: ['d2admin', 'ui'],
    name: 'd2admin文档',
  },
  {
    homepage: 'https://wanago.io/2021/01/25/api-nestjs-chat-websockets/',
    icon: 'link.png',
    keywords: ['nestjs', 'backend', 'websocket', 'api'],
    name: 'NestjsChat',
  },
  {
    homepage: 'https://docs.opencloudos.org/OCS/Virtualization_and_Containers_Guide/Docker_guide/',
    icon: 'link.png',
    keywords: ['open', 'os', 'cloud', 'docker'],
    name: 'OpenCloudOS',
  },
  {
    homepage: 'https://www.likebookmark.com/',
    icon: 'likebookmark.png',
    keywords: ['bookmark', 'mark', 'shuqian', 'sq'],
    name: '喜欢书签',
  },
  {
    homepage: 'https://biemoyu.com/',
    icon: 'link.png',
    keywords: ['bmy', 'mark', 'shuqian', 'sq'],
    name: '别摸鱼导航',
  },
  {
    homepage: 'https://www.istoreos.com/',
    icon: 'link.png',
    keywords: ['router','os','istoreos','云存储','路由','网络存储','存储','NAS'],
    name: 'iStoreOS网络存储',
  },
  {
    homepage: 'https://www.topgoer.com/',
    icon: 'link.png',
    keywords: ['golang', 'go', 'client'],
    name: 'Go学习',
  },
  {
    homepage: 'https://www.nushell.sh/zh-CN/',
    icon: 'link.png',
    keywords: ['nushell', 'sh', 'shell'],
    name: 'NuShell',
  }
]
