name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    if: github.repository == 'xushuyi888/test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: npx pnpm i && npm run build

      - name: Clone website repo
        uses: GuillaumeFalourd/clone-github-repo-action@v1
        with:
          owner: hello-nav
          repository: hello-nav.github.io
          access-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy
        run: |
          sudo chown -R $USER:$USER ./hello-nav.github.io
          cd hello-nav.github.io
          rm -rf ./*
          cp -r ../dist/* ./
          git config --global user.name ${{ secrets.REPO_USER }}
          git config --global user.email ${{ secrets.REPO_EMAIL }}
          git add .
          git commit -m 'CI BUILD'
          git push origin master
